name: flutter_cache_manager_firebase
description: CacheManager implementation for firebase_storage. Uses the gs:// as key and translates to https://
version: 2.0.1
homepage: https://github.com/Baseflow/flutter_cache_manager

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/prashantsolankispaceo/flutter_cache_manager.git
      path: flutter_cache_manager
  firebase_storage:
    git:
      url: https://github.com/prashantsolankispaceo/firebase_storage.git
      path: firebase_storage
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
